Combine if-then blocks into if-then-elif block.

diff --git a/modules/nf-core/gtdbtk/classifywf/gtdbtk-classifywf.diff b/modules/nf-core/gtdbtk/classifywf/gtdbtk-classifywf.diff
--- a/modules/nf-core/gtdbtk/classifywf/gtdbtk-classifywf.diff
+++ b/modules/nf-core/gtdbtk/classifywf/gtdbtk-classifywf.diff
@@ -4,17 +4,16 @@ Changes in component 'nf-core/gtdbtk/classifywf'
 Changes in 'gtdbtk/classifywf/main.nf':
 --- modules/nf-core/gtdbtk/classifywf/main.nf
 +++ modules/nf-core/gtdbtk/classifywf/main.nf
-@@ -32,7 +32,13 @@
+@@ -32,7 +32,12 @@
      prefix = task.ext.prefix ?: "${meta.id}"
  
      """
 -    export GTDBTK_DATA_PATH="\$(find -L ${db} -name 'metadata' -type d -exec dirname {} \\;)"#
-+    if [ -z "$db" ] && [ -z "\$GTDBTK_DATA_PATH" ]; then
-+        echo "Error ${task.process}( ${task.index} ): input `db` is null, but environment variable GTDBTK_DATA_PATH is not set."
-+        exit 1
-+    fi
-+    if [ -n "$db" ] && [ -z "\$GTDBTK_DATA_PATH" ]; then
++    if [ -n "$db" ]; then
 +        export GTDBTK_DATA_PATH="\$(find -L ${db} -name 'metadata' -type d -exec dirname {} \\;)"
++    elif [ -z "\$GTDBTK_DATA_PATH" ]; then
++        echo "Error ${task.process}( ${task.tag} ): input `db` is null, but environment variable GTDBTK_DATA_PATH is not set."
++        exit 1
 +    fi
  
      if [ ${pplacer_scratch} != "" ] ; then
